easy_admin:
    site_name: Star Wars
    design:
        menu:
            - label: Dashboard
              icon: dashboard
              route: roll_dashboard
            - label: Roller
              route: roll_board
            - label: Viewer
              route: roll_viewer
    
