security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 13

    providers:
        user_doctrine:
            entity:
                class: AppBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            stateless: false
            guard:
                authenticator: user_authenticator
            provider: user_doctrine
            form_login:
                login_path: /login
            logout: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/roll, roles: ROLE_USER }
